# Generated by Django 3.2 on 2023-06-01 17:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userstuff', '0002_auto_20230601_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to='userstuff.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='user_following', to='userstuff.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='public_playlist',
            field=models.ManyToManyField(null=True, related_name='public_playlist', to='userstuff.Song'),
        ),
    ]
